syntax = "proto3";
package accounts.v1;

import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";

// option go_package = "github.com/cdialpha/pfd/gen/go/accounts/v1;accountspb";

service AccountsService {
  rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse);
  rpc ListAccounts(ListAccountsRequest) returns (ListAccountsResponse);
  rpc GetAccount(GetAccountRequest) returns (GetAccountResponse);
  rpc UpdateAccount(UpdateAccountRequest) returns (UpdateAccountResponse);
  rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);
}

message CreateAccountRequest {
  string name = 1;
  string email = 2;
}

message CreateAccountResponse {
  Account account = 1;
}

message GetAccountRequest {
  string account_id = 1;
}

message GetAccountResponse {
  Account account = 1;
}

message ListAccountsRequest {
  int32 page_size = 1;
  string page_token = 2;
}

message ListAccountsResponse {
  repeated Account accounts = 1;
  string next_page_token = 2;
}

message UpdateAccountRequest {
  string account_id = 1;
  Account account = 2;
  google.protobuf.FieldMask update_mask = 3;
}

message UpdateAccountResponse {
  Account account = 1;
}

message DeleteAccountRequest {
  string account_id = 1;
}

message DeleteAccountResponse {
  Account account = 1; // return deleted account metadata for confirmation
}

message Account {
  string id = 1;
  string name = 2;
  string email = 3;
  google.protobuf.Timestamp created_at = 4;
}

enum Environment {
  ENVIRONMENT_UNSPECIFIED = 0;
  ENVIRONMENT_TEST = 1;
  ENVIRONMENT_LIVE = 2;
}
