FROM golang:1.26-alpine3.24 AS builder

WORKDIR /app

# Install protoc and dependencies
# Use only if compiling .proto files inside this Dockerfile
# RUN apk add --no-cache protobuf protobuf-dev

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .


# Build app
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o account-server ./cmd/accounts-server/main.go

# Final stage   
FROM alpine:3.24

# Add ca-certificates for TLS and grpc-health-probe
RUN apk --no-cache add ca-certificates

# Install grpc-health-probe
RUN GRPC_HEALTH_PROBE_VERSION=v0.4.24 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

# 2. Setup user permissions before moving files
RUN adduser -D -g '' appuser
WORKDIR /app

# 2. Grant ownership directly to non-root user during copy
COPY --from=builder --chown=appuser:appuser /app/account-server .

USER appuser

# Expose gRPC port
EXPOSE 50051

# Run the server
CMD ["./account-server"]