.PHONY: up down # status, deploy, reset, 

up: 
	@echo "Starting local K8s cluster with Kind..."
	bash ./scripts/up.sh

down: 
	@echo "Stopping local K8s cluster with Kind..."
	bash ./scripts/down.sh
