services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pw
    env_file:
      - .env
    secrets:
      - pg_pw
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  
secrets :
  pg_pw:
    file: ./.secrets/pg_pw.txt