apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/cdialpha/pfd/
    path: deploy/manifests/cert-manager
    directory:
      recurse: true
      # include: "*.yaml"
      # exlucde: "{kustomization.yaml, *.md}"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply: true
      - Replace: true
      - CreateNamespace: true