apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
  -  repoURL: https://charts.jetstack.io
     chart: cert-manager
     targetRevision: v1.20.3
     helm:
       valueFiles:
       - $values/deploy/charts/cert-manager/cert-manager-values.yaml
  -  repoURL: https://github.com/cdialpha/pfd 
     targetRevision: dev 
     ref: values    
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
      - CreateNamespace=true