apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  sources:
  -  repoURL: https://helm.cilium.io/
     chart: cilium
     targetRevision: 1.19.4
     helm:
       valueFiles:
       - $values/deploy/values/cilium-values.yaml
  -  repoURL: https://github.com/cdialpha/pfd 
     targetRevision: dev 
     ref: values     
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m